# Native Closure Rules

"""
    CompiledRule{F, S} <: UpdateRule

A highly optimized native Julia closure rule generated by the `@rule` macro.

# Type Parameters
- `F`: The type of the native function closure `(cell_data, cell_id, ctx) -> ...`
- `S`: The type of the spatial metadata tuple `(ContactArea(...), ...)`

# Fields
- `func::F`: The native function to execute on the GPU.
- `spatial_rules::S`: The tuple of spatial extraction rules required by this closure.
"""
struct CompiledRule{F, S} <: UpdateRule
    func::F
    spatial_rules::S
end

CompiledRule(func) = CompiledRule(func, ())
